# For local phase configurations
server:
  port: 54000
  
spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: com.holdings.dbconfig.CustomOracleDialect
  output:
    ansi:
      enabled: always
      
springdoc:
  version: '1.0.0'
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match: /**
  
logging:
  level: error
  pattern:
    file: %d %p %c{1.} [%t] %m%n
    console:  %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
  file:
    path: C:/logs/holdingsAPI/holdingsAPI.log
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.20.101.17:1531/test1
    username: apps
    password: apps

---
#spring:
#  config:
#    activate:
#      on-profile: alpha
#  profiles:
#    include: test
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@merp2010a:1522/prod
#    username: apps
#    password: apps

file:
  upload-dir: C:\ftp

